### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by Kampfkarren** [buildthomas/MockDataStoreService#11]
I want to get MockDataStoreService working so I can test DataStore2 (and possibly push this upstream into Lemur as the default DataStoreService implementation), I'll try and add as much as necessary until my local copy stops erroring, then push upstream.

Issues that need figuring out:

LPGhatguy/lemur#115

**Comment by Kampfkarren** [comment]
Fat fingered Ctrl+Enter for the original title, whoops.

**Comment by buildthomas** [comment]
No longer using Lemur, testing via separate test place file via #14.
