### ISSUE TITLE
Create Downloadable rbmx Source File

### ISSUE THREAD

**Issue by RuizuKun-Dev** [buildthomas/MockDataStoreService#17]
- MockDataStore has a lot of sub modules and it is annoying to copy everything multiple times initially and upon updates.
creating a Release or Downloadable Source file would improve user experience greatly (not everyone uses Rojo)

**Comment by NobleDraconian** [comment]
@buildthomas If you intend to use github actions for this, here's an example of what I do for my automated releases : https://github.com/NobleDraconian/Dragon-Engine/blob/master/.github/workflows/release.yml

**Comment by buildthomas** [comment]
Done, thanks @NobleDraconian

**Comment by buildthomas** [comment]
Actually looks like the generated file doesn't work with Studio yet, I'll debug later

**Comment by buildthomas** [comment]
@RuizuKun-Dev this is done, whenever master changes it now creates a release that I can publish like this:

https://github.com/buildthomas/MockDataStoreService/releases/tag/1.0.1

Thanks for suggesting
